name: socket_io_client
description: socket.io client
version: 0.0.1
author: long1eu<home@long1.eu>
homepage:

environment:
  sdk: "<=3.0.0"

dependencies:
  logging: any
  stream: any
  uuid: any
  utf: ^0.9.0+4
  cookie_jar:
    git: https://github.com/flutterchina/cookie_jar.git
  engine_io_client:
    git:
      url: https://github.com/long1eu/engine_io_client
      ref: from_java
    #path: ../engine_io_client

dev_dependencies:
  test: any

