name: socket_io_client
description: socket.io client
version: 0.0.1
author:
homepage:

dependencies:
  logging: any
  stream: any
  uuid: any
  utf: ^0.9.0+4
  web_socket_channel: ^1.0.7
  engine_io_client:
    git: https://github.com/long1eu/socket_io_engine
    #path: ../engine_io_client

dev_dependencies:
  test: any

environment:
  sdk: "<=3.0.0"